### PR TITLE
refactor controller routes

### PR DESCRIPTION
**Pull request by Lucasal072**
remove redundant code from decorators/controller routes and add a helper in decorators/helpers

### CODE REVIEW

**Review by seujorgenochurras — APPROVED** [review]
Nice work dude, this library really needs a clean up

**Comment by ItayTheDar** [comment]
This library needs co-maintainer! 😆😆

**Review by ItayTheDar — APPROVED** [review]

**Comment by ItayTheDar** [comment]
@Lucasal072 Greate job man! thank you so much for this effort 🥇

**Comment by AddeJhow** [comment]
Nice! Great job @Lucasal072

**Pull request merged**
