### PR TITLE
Update deploy_docs.yaml

### PR DESCRIPTION
**Pull request by ItayTheDar**

### CODE REVIEW

**Comment by dev0Guy** [comment]
Hi , 
I see the changes has been added into main, however the docs server itself didn't update. Any idea way?

**Comment by dev0Guy** [comment]
Hi ,
Two things I'v noticed,  The logo size has not change (is smaller than i see in my localmachine with 'poetry run mkdocs serve'). 
Second thing is the logo in the first page https://PyNest.github.io/PyNest/ when clicking on the logo the link is for https://pythonnest.github.io/ . 
I don't see how my changes has cause that, will be happy to help :)

**Comment by itay-dar-lmnd** [comment]
> Hi , Two things I'v noticed, The logo size has not change (is smaller than i see in my localmachine with 'poetry run mkdocs serve'). Second thing is the logo in the first page https://PyNest.github.io/PyNest/ when clicking on the logo the link is for https://pythonnest.github.io/ . I don't see how my changes has cause that, will be happy to help :)

About the second thing, i think it's a bug, i guess somewhere in the index.html file there is a way to fix. and about the logo, it seems just fine, you wanted it to be bigger?

**Comment by dev0Guy** [comment]
I've notice now the logo size as been fixed. I guess the assets were cached or the css was not loaded in my client..

**Pull request merged**
